// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFirewallRule(arg1) {
  return window['go']['main']['App']['AddFirewallRule'](arg1);
}

export function AllowDockerDatabaseAccess(arg1, arg2) {
  return window['go']['main']['App']['AllowDockerDatabaseAccess'](arg1, arg2);
}

export function ApplyComposeConfig(arg1, arg2) {
  return window['go']['main']['App']['ApplyComposeConfig'](arg1, arg2);
}

export function ChmodFile(arg1) {
  return window['go']['main']['App']['ChmodFile'](arg1);
}

export function CloseServerTab(arg1) {
  return window['go']['main']['App']['CloseServerTab'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CompressFiles(arg1) {
  return window['go']['main']['App']['CompressFiles'](arg1);
}

export function CopyFiles(arg1) {
  return window['go']['main']['App']['CopyFiles'](arg1);
}

export function CreateDockerNetwork(arg1) {
  return window['go']['main']['App']['CreateDockerNetwork'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateWebsite(arg1) {
  return window['go']['main']['App']['CreateWebsite'](arg1);
}

export function CreateWebsiteCronJob(arg1) {
  return window['go']['main']['App']['CreateWebsiteCronJob'](arg1);
}

export function CreateWebsiteDatabase(arg1) {
  return window['go']['main']['App']['CreateWebsiteDatabase'](arg1);
}

export function CreateWebsiteDatabaseUser(arg1) {
  return window['go']['main']['App']['CreateWebsiteDatabaseUser'](arg1);
}

export function CreateWebsiteSFTPAccount(arg1) {
  return window['go']['main']['App']['CreateWebsiteSFTPAccount'](arg1);
}

export function CreateWebsiteSubdomain(arg1) {
  return window['go']['main']['App']['CreateWebsiteSubdomain'](arg1);
}

export function DbXferCancel(arg1) {
  return window['go']['main']['App']['DbXferCancel'](arg1);
}

export function DbXferListTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['DbXferListTables'](arg1, arg2, arg3);
}

export function DbXferStart(arg1) {
  return window['go']['main']['App']['DbXferStart'](arg1);
}

export function DbXferStatus(arg1) {
  return window['go']['main']['App']['DbXferStatus'](arg1);
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeleteFirewallRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFirewallRule'](arg1, arg2, arg3);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteWebsite(arg1) {
  return window['go']['main']['App']['DeleteWebsite'](arg1);
}

export function DeleteWebsiteCronJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteWebsiteCronJob'](arg1, arg2, arg3);
}

export function DeleteWebsiteProxyRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteWebsiteProxyRule'](arg1, arg2, arg3);
}

export function DeleteWebsiteSFTPAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteWebsiteSFTPAccount'](arg1, arg2, arg3);
}

export function DetectDockerEngine(arg1) {
  return window['go']['main']['App']['DetectDockerEngine'](arg1);
}

export function DetectDockerSubnets(arg1) {
  return window['go']['main']['App']['DetectDockerSubnets'](arg1);
}

export function DetectNginxEngine(arg1) {
  return window['go']['main']['App']['DetectNginxEngine'](arg1);
}

export function DisableWebsiteDBDockerAccess(arg1, arg2) {
  return window['go']['main']['App']['DisableWebsiteDBDockerAccess'](arg1, arg2);
}

export function DisableWebsitePHP(arg1, arg2) {
  return window['go']['main']['App']['DisableWebsitePHP'](arg1, arg2);
}

export function DisableWebsiteProxyDomain(arg1, arg2) {
  return window['go']['main']['App']['DisableWebsiteProxyDomain'](arg1, arg2);
}

export function DisableWebsiteSSL(arg1, arg2) {
  return window['go']['main']['App']['DisableWebsiteSSL'](arg1, arg2);
}

export function DockerContainerLogs(arg1) {
  return window['go']['main']['App']['DockerContainerLogs'](arg1);
}

export function DockerContainerStats(arg1, arg2) {
  return window['go']['main']['App']['DockerContainerStats'](arg1, arg2);
}

export function DockerXferCancel(arg1) {
  return window['go']['main']['App']['DockerXferCancel'](arg1);
}

export function DockerXferStart(arg1) {
  return window['go']['main']['App']['DockerXferStart'](arg1);
}

export function DockerXferStatus(arg1) {
  return window['go']['main']['App']['DockerXferStatus'](arg1);
}

export function DownloadFileFromServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFileFromServer'](arg1, arg2, arg3);
}

export function DropWebsiteDatabase(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropWebsiteDatabase'](arg1, arg2, arg3);
}

export function DropWebsiteDatabaseUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropWebsiteDatabaseUser'](arg1, arg2, arg3, arg4);
}

export function EnableWebsiteSSL(arg1, arg2) {
  return window['go']['main']['App']['EnableWebsiteSSL'](arg1, arg2);
}

export function EnableWebsiteSSLAutoRenew(arg1, arg2) {
  return window['go']['main']['App']['EnableWebsiteSSLAutoRenew'](arg1, arg2);
}

export function EnsureWebsiteDBDockerAccess(arg1, arg2) {
  return window['go']['main']['App']['EnsureWebsiteDBDockerAccess'](arg1, arg2);
}

export function ExportBackup(arg1, arg2) {
  return window['go']['main']['App']['ExportBackup'](arg1, arg2);
}

export function ExportWebsiteDNSZone(arg1, arg2) {
  return window['go']['main']['App']['ExportWebsiteDNSZone'](arg1, arg2);
}

export function ExtractArchive(arg1) {
  return window['go']['main']['App']['ExtractArchive'](arg1);
}

export function ForgetWebsiteDBCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ForgetWebsiteDBCredential'](arg1, arg2, arg3, arg4);
}

export function GetComposeStatus(arg1, arg2) {
  return window['go']['main']['App']['GetComposeStatus'](arg1, arg2);
}

export function GetSystemService(arg1, arg2) {
  return window['go']['main']['App']['GetSystemService'](arg1, arg2);
}

export function GetWebsiteDBDockerAccessStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteDBDockerAccessStatus'](arg1, arg2);
}

export function GetWebsiteDBPrivileges() {
  return window['go']['main']['App']['GetWebsiteDBPrivileges']();
}

export function GetWebsiteDBStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteDBStatus'](arg1, arg2);
}

export function GetWebsiteDBVersions(arg1) {
  return window['go']['main']['App']['GetWebsiteDBVersions'](arg1);
}

export function GetWebsiteDNSPreview(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteDNSPreview'](arg1, arg2);
}

export function GetWebsiteDomainRoot(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteDomainRoot'](arg1, arg2);
}

export function GetWebsiteLog(arg1) {
  return window['go']['main']['App']['GetWebsiteLog'](arg1);
}

export function GetWebsitePHPStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebsitePHPStatus'](arg1, arg2);
}

export function GetWebsiteProxyStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteProxyStatus'](arg1, arg2);
}

export function GetWebsiteSSLStatus(arg1, arg2) {
  return window['go']['main']['App']['GetWebsiteSSLStatus'](arg1, arg2);
}

export function GrantWebsiteDatabaseUser(arg1) {
  return window['go']['main']['App']['GrantWebsiteDatabaseUser'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function InspectDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['InspectDockerContainer'](arg1, arg2);
}

export function IssueWebsiteSSL(arg1) {
  return window['go']['main']['App']['IssueWebsiteSSL'](arg1);
}

export function LinkWebsiteDomainDatabase(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LinkWebsiteDomainDatabase'](arg1, arg2, arg3, arg4);
}

export function ListDockerContainers(arg1) {
  return window['go']['main']['App']['ListDockerContainers'](arg1);
}

export function ListDockerNetworks(arg1) {
  return window['go']['main']['App']['ListDockerNetworks'](arg1);
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function ListFirewallRules(arg1, arg2) {
  return window['go']['main']['App']['ListFirewallRules'](arg1, arg2);
}

export function ListServerStatuses() {
  return window['go']['main']['App']['ListServerStatuses']();
}

export function ListServerTabs() {
  return window['go']['main']['App']['ListServerTabs']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSystemServices(arg1) {
  return window['go']['main']['App']['ListSystemServices'](arg1);
}

export function ListSystemUsers(arg1) {
  return window['go']['main']['App']['ListSystemUsers'](arg1);
}

export function ListWebsiteCronJobs(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteCronJobs'](arg1, arg2);
}

export function ListWebsiteDBCredentials(arg1) {
  return window['go']['main']['App']['ListWebsiteDBCredentials'](arg1);
}

export function ListWebsiteDatabaseUsers(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteDatabaseUsers'](arg1, arg2);
}

export function ListWebsiteDatabases(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteDatabases'](arg1, arg2);
}

export function ListWebsiteDomainDatabases(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteDomainDatabases'](arg1, arg2);
}

export function ListWebsiteServerDatabaseDomains(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteServerDatabaseDomains'](arg1, arg2);
}

export function ListWebsiteSFTPAccounts(arg1, arg2) {
  return window['go']['main']['App']['ListWebsiteSFTPAccounts'](arg1, arg2);
}

export function ListWebsites(arg1) {
  return window['go']['main']['App']['ListWebsites'](arg1);
}

export function MySQLExploreDeleteRow(arg1) {
  return window['go']['main']['App']['MySQLExploreDeleteRow'](arg1);
}

export function MySQLExploreExecuteQuery(arg1) {
  return window['go']['main']['App']['MySQLExploreExecuteQuery'](arg1);
}

export function MySQLExploreInsertRow(arg1) {
  return window['go']['main']['App']['MySQLExploreInsertRow'](arg1);
}

export function MySQLExploreListColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['MySQLExploreListColumns'](arg1, arg2, arg3);
}

export function MySQLExploreListDatabases(arg1) {
  return window['go']['main']['App']['MySQLExploreListDatabases'](arg1);
}

export function MySQLExploreListTables(arg1, arg2) {
  return window['go']['main']['App']['MySQLExploreListTables'](arg1, arg2);
}

export function MySQLExploreTableRows(arg1) {
  return window['go']['main']['App']['MySQLExploreTableRows'](arg1);
}

export function MySQLExploreUpdateRow(arg1) {
  return window['go']['main']['App']['MySQLExploreUpdateRow'](arg1);
}

export function OpenDockerExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenDockerExec'](arg1, arg2, arg3);
}

export function OpenMigrationTab(arg1) {
  return window['go']['main']['App']['OpenMigrationTab'](arg1);
}

export function OpenServerTab(arg1, arg2) {
  return window['go']['main']['App']['OpenServerTab'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PGExploreDeleteRow(arg1) {
  return window['go']['main']['App']['PGExploreDeleteRow'](arg1);
}

export function PGExploreExecuteQuery(arg1) {
  return window['go']['main']['App']['PGExploreExecuteQuery'](arg1);
}

export function PGExploreInsertRow(arg1) {
  return window['go']['main']['App']['PGExploreInsertRow'](arg1);
}

export function PGExploreListColumns(arg1, arg2) {
  return window['go']['main']['App']['PGExploreListColumns'](arg1, arg2);
}

export function PGExploreListDatabases(arg1) {
  return window['go']['main']['App']['PGExploreListDatabases'](arg1);
}

export function PGExploreListTables(arg1) {
  return window['go']['main']['App']['PGExploreListTables'](arg1);
}

export function PGExploreTableRows(arg1) {
  return window['go']['main']['App']['PGExploreTableRows'](arg1);
}

export function PGExploreUpdateRow(arg1) {
  return window['go']['main']['App']['PGExploreUpdateRow'](arg1);
}

export function ReadFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2, arg3);
}

export function ReadSystemJournal(arg1) {
  return window['go']['main']['App']['ReadSystemJournal'](arg1);
}

export function ReadWebsiteCronLog(arg1) {
  return window['go']['main']['App']['ReadWebsiteCronLog'](arg1);
}

export function RecreateDockerContainer(arg1) {
  return window['go']['main']['App']['RecreateDockerContainer'](arg1);
}

export function RefreshServerStatus(arg1) {
  return window['go']['main']['App']['RefreshServerStatus'](arg1);
}

export function ReloadFirewall(arg1) {
  return window['go']['main']['App']['ReloadFirewall'](arg1);
}

export function RemoveDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveDockerContainer'](arg1, arg2);
}

export function RemoveDockerNetwork(arg1, arg2) {
  return window['go']['main']['App']['RemoveDockerNetwork'](arg1, arg2);
}

export function RenameFile(arg1) {
  return window['go']['main']['App']['RenameFile'](arg1);
}

export function RenewWebsiteSSL(arg1, arg2) {
  return window['go']['main']['App']['RenewWebsiteSSL'](arg1, arg2);
}

export function ReorderServerTabs(arg1) {
  return window['go']['main']['App']['ReorderServerTabs'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['RestartDockerContainer'](arg1, arg2);
}

export function RevokeWebsiteDatabaseUser(arg1) {
  return window['go']['main']['App']['RevokeWebsiteDatabaseUser'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SaveWebsiteDBCredential(arg1) {
  return window['go']['main']['App']['SaveWebsiteDBCredential'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SetFirewallEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetFirewallEnabled'](arg1, arg2);
}

export function SetTabActiveModule(arg1, arg2) {
  return window['go']['main']['App']['SetTabActiveModule'](arg1, arg2);
}

export function SetWebsiteDatabaseGrants(arg1) {
  return window['go']['main']['App']['SetWebsiteDatabaseGrants'](arg1);
}

export function SetWebsiteEnabled(arg1) {
  return window['go']['main']['App']['SetWebsiteEnabled'](arg1);
}

export function SetWebsitePHP(arg1) {
  return window['go']['main']['App']['SetWebsitePHP'](arg1);
}

export function SetWebsiteProxyDomain(arg1) {
  return window['go']['main']['App']['SetWebsiteProxyDomain'](arg1);
}

export function SetWebsiteProxyRule(arg1) {
  return window['go']['main']['App']['SetWebsiteProxyRule'](arg1);
}

export function StartDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['StartDockerContainer'](arg1, arg2);
}

export function StartDockerEngine(arg1) {
  return window['go']['main']['App']['StartDockerEngine'](arg1);
}

export function StartNginxEngine(arg1) {
  return window['go']['main']['App']['StartNginxEngine'](arg1);
}

export function StartWebsiteDB(arg1, arg2) {
  return window['go']['main']['App']['StartWebsiteDB'](arg1, arg2);
}

export function StopDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['StopDockerContainer'](arg1, arg2);
}

export function StopDockerStream(arg1) {
  return window['go']['main']['App']['StopDockerStream'](arg1);
}

export function StreamDockerContainerLogs(arg1) {
  return window['go']['main']['App']['StreamDockerContainerLogs'](arg1);
}

export function StreamDockerContainerStats(arg1, arg2) {
  return window['go']['main']['App']['StreamDockerContainerStats'](arg1, arg2);
}

export function StreamDockerEngineInstall(arg1) {
  return window['go']['main']['App']['StreamDockerEngineInstall'](arg1);
}

export function StreamSystemJournal(arg1) {
  return window['go']['main']['App']['StreamSystemJournal'](arg1);
}

export function StreamWebsiteInstall(arg1, arg2, arg3) {
  return window['go']['main']['App']['StreamWebsiteInstall'](arg1, arg2, arg3);
}

export function StreamWebsiteLog(arg1) {
  return window['go']['main']['App']['StreamWebsiteLog'](arg1);
}

export function SystemServiceAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SystemServiceAction'](arg1, arg2, arg3);
}

export function TestServerConnection(arg1) {
  return window['go']['main']['App']['TestServerConnection'](arg1);
}

export function ToggleWebsiteCronJob(arg1) {
  return window['go']['main']['App']['ToggleWebsiteCronJob'](arg1);
}

export function TrustServerHostKey(arg1) {
  return window['go']['main']['App']['TrustServerHostKey'](arg1);
}

export function UnlinkWebsiteDomainDatabase(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnlinkWebsiteDomainDatabase'](arg1, arg2, arg3, arg4);
}

export function UpdateWebsiteCronJob(arg1) {
  return window['go']['main']['App']['UpdateWebsiteCronJob'](arg1);
}

export function UploadFilesToServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFilesToServer'](arg1, arg2, arg3);
}

export function WriteFileContent(arg1) {
  return window['go']['main']['App']['WriteFileContent'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}

export function XferCancel(arg1) {
  return window['go']['main']['App']['XferCancel'](arg1);
}

export function XferListDirectory(arg1, arg2) {
  return window['go']['main']['App']['XferListDirectory'](arg1, arg2);
}

export function XferStart(arg1) {
  return window['go']['main']['App']['XferStart'](arg1);
}

export function XferStatus(arg1) {
  return window['go']['main']['App']['XferStatus'](arg1);
}
