// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {servers} from '../models';

export function CloseServerTab(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function ListServerTabs():Promise<Array<session.Tab>>;

export function ListServers():Promise<Array<servers.Server>>;

export function OpenServerTab(arg1:string,arg2:string):Promise<session.Tab>;

export function ReorderServerTabs(arg1:Array<string>):Promise<void>;

export function SaveServer(arg1:servers.SaveServerRequest):Promise<servers.Server>;

export function SetTabActiveModule(arg1:string,arg2:string):Promise<void>;

export function TestServerConnection(arg1:servers.SaveServerRequest):Promise<servers.ConnectionTestResult>;

export function TrustServerHostKey(arg1:servers.SaveServerRequest):Promise<void>;
