// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChmodFile(arg1) {
  return window['go']['main']['App']['ChmodFile'](arg1);
}

export function CloseServerTab(arg1) {
  return window['go']['main']['App']['CloseServerTab'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CompressFiles(arg1) {
  return window['go']['main']['App']['CompressFiles'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadFileFromServer(arg1, arg2) {
  return window['go']['main']['App']['DownloadFileFromServer'](arg1, arg2);
}

export function ExtractArchive(arg1) {
  return window['go']['main']['App']['ExtractArchive'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListServerStatuses() {
  return window['go']['main']['App']['ListServerStatuses']();
}

export function ListServerTabs() {
  return window['go']['main']['App']['ListServerTabs']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function OpenServerTab(arg1, arg2) {
  return window['go']['main']['App']['OpenServerTab'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function RefreshServerStatus(arg1) {
  return window['go']['main']['App']['RefreshServerStatus'](arg1);
}

export function RenameFile(arg1) {
  return window['go']['main']['App']['RenameFile'](arg1);
}

export function ReorderServerTabs(arg1) {
  return window['go']['main']['App']['ReorderServerTabs'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SetTabActiveModule(arg1, arg2) {
  return window['go']['main']['App']['SetTabActiveModule'](arg1, arg2);
}

export function TestServerConnection(arg1) {
  return window['go']['main']['App']['TestServerConnection'](arg1);
}

export function TrustServerHostKey(arg1) {
  return window['go']['main']['App']['TrustServerHostKey'](arg1);
}

export function UploadFilesToServer(arg1, arg2) {
  return window['go']['main']['App']['UploadFilesToServer'](arg1, arg2);
}

export function WriteFileContent(arg1) {
  return window['go']['main']['App']['WriteFileContent'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
