// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {files} from '../models';
import {docker} from '../models';
import {website} from '../models';
import {servers} from '../models';
import {session} from '../models';

export function ChmodFile(arg1:files.ChmodRequest):Promise<void>;

export function CloseServerTab(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CompressFiles(arg1:files.CompressRequest):Promise<void>;

export function CopyFiles(arg1:files.CopyRequest):Promise<void>;

export function CreateDockerNetwork(arg1:docker.NetworkCreateRequest):Promise<docker.NetworkInfo>;

export function CreateFile(arg1:files.CreateFileRequest):Promise<void>;

export function CreateFolder(arg1:files.MkdirRequest):Promise<void>;

export function CreateWebsite(arg1:website.CreateWebsiteRequest):Promise<website.CreateWebsiteResult>;

export function CreateWebsiteCronJob(arg1:website.CronJobRequest):Promise<website.CronJobInfo>;

export function CreateWebsiteDatabase(arg1:website.DBCreateDatabaseRequest):Promise<void>;

export function CreateWebsiteDatabaseUser(arg1:website.DBCreateUserRequest):Promise<void>;

export function CreateWebsiteSFTPAccount(arg1:website.SFTPCreateAccountRequest):Promise<void>;

export function CreateWebsiteSubdomain(arg1:website.CreateSubdomainRequest):Promise<website.DomainInfo>;

export function DeleteFiles(arg1:files.DeleteRequest):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteWebsite(arg1:website.DeleteDomainRequest):Promise<void>;

export function DeleteWebsiteCronJob(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteWebsiteProxyRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteWebsiteSFTPAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DetectDockerEngine(arg1:string):Promise<docker.EngineStatus>;

export function DetectNginxEngine(arg1:string):Promise<website.NginxStatus>;

export function DisableWebsitePHP(arg1:string,arg2:string):Promise<void>;

export function DisableWebsiteProxyDomain(arg1:string,arg2:string):Promise<void>;

export function DisableWebsiteSSL(arg1:string,arg2:string):Promise<website.SSLStatus>;

export function DockerContainerLogs(arg1:docker.LogsRequest):Promise<docker.LogsResponse>;

export function DockerContainerStats(arg1:string,arg2:string):Promise<docker.StatsResponse>;

export function DownloadFileFromServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EnableWebsiteSSL(arg1:string,arg2:string):Promise<website.SSLStatus>;

export function EnableWebsiteSSLAutoRenew(arg1:string,arg2:string):Promise<website.SSLStatus>;

export function ExportWebsiteDNSZone(arg1:string,arg2:string):Promise<void>;

export function ExtractArchive(arg1:files.ExtractRequest):Promise<void>;

export function GetWebsiteDBPrivileges():Promise<Array<website.DBPrivilegeOption>>;

export function GetWebsiteDBStatus(arg1:string,arg2:string):Promise<website.DBEngineStatus>;

export function GetWebsiteDNSPreview(arg1:string,arg2:string):Promise<website.DNSPreviewResponse>;

export function GetWebsiteDomainRoot(arg1:string,arg2:string):Promise<string>;

export function GetWebsiteLog(arg1:website.LogReadRequest):Promise<website.LogReadResponse>;

export function GetWebsitePHPStatus(arg1:string,arg2:string):Promise<website.PHPStatus>;

export function GetWebsiteProxyStatus(arg1:string,arg2:string):Promise<website.ProxyStatus>;

export function GetWebsiteSSLStatus(arg1:string,arg2:string):Promise<website.SSLStatus>;

export function InspectDockerContainer(arg1:string,arg2:string):Promise<docker.ContainerInspectResponse>;

export function IssueWebsiteSSL(arg1:website.SSLIssueRequest):Promise<website.SSLStatus>;

export function ListDockerContainers(arg1:string):Promise<docker.ListResponse>;

export function ListDockerNetworks(arg1:string):Promise<docker.NetworkListResponse>;

export function ListFiles(arg1:string,arg2:string,arg3:string):Promise<files.ListResult>;

export function ListServerStatuses():Promise<Array<servers.ServerStatus>>;

export function ListServerTabs():Promise<Array<session.Tab>>;

export function ListServers():Promise<Array<servers.Server>>;

export function ListSystemUsers(arg1:string):Promise<Array<files.SystemUser>>;

export function ListWebsiteCronJobs(arg1:string,arg2:string):Promise<website.CronListResponse>;

export function ListWebsiteDatabaseUsers(arg1:string,arg2:string):Promise<Array<website.DBUserInfo>>;

export function ListWebsiteDatabases(arg1:string,arg2:string):Promise<Array<website.DBDatabaseInfo>>;

export function ListWebsiteSFTPAccounts(arg1:string,arg2:string):Promise<website.SFTPListResponse>;

export function ListWebsites(arg1:string):Promise<website.ListResponse>;

export function OpenDockerExec(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenServerTab(arg1:string,arg2:string):Promise<session.Tab>;

export function OpenTerminal(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string,arg2:string,arg3:string):Promise<files.ReadResult>;

export function ReadWebsiteCronLog(arg1:website.CronLogRequest):Promise<website.CronLogResponse>;

export function RecreateDockerContainer(arg1:docker.RecreateContainerRequest):Promise<docker.RecreateContainerResponse>;

export function RefreshServerStatus(arg1:string):Promise<servers.ServerStatus>;

export function RemoveDockerContainer(arg1:string,arg2:string):Promise<void>;

export function RemoveDockerNetwork(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:files.RenameRequest):Promise<void>;

export function RenewWebsiteSSL(arg1:string,arg2:string):Promise<website.SSLStatus>;

export function ReorderServerTabs(arg1:Array<string>):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartDockerContainer(arg1:string,arg2:string):Promise<void>;

export function SaveServer(arg1:servers.SaveServerRequest):Promise<servers.Server>;

export function SearchFiles(arg1:files.SearchRequest):Promise<files.SearchResult>;

export function SetTabActiveModule(arg1:string,arg2:string):Promise<void>;

export function SetWebsiteDatabaseGrants(arg1:website.DBGrantsRequest):Promise<void>;

export function SetWebsiteEnabled(arg1:website.SetEnabledRequest):Promise<void>;

export function SetWebsitePHP(arg1:website.PHPSetDomainRequest):Promise<void>;

export function SetWebsiteProxyDomain(arg1:website.ProxySetDomainRequest):Promise<void>;

export function SetWebsiteProxyRule(arg1:website.ProxyRuleRequest):Promise<void>;

export function StartDockerContainer(arg1:string,arg2:string):Promise<void>;

export function StartDockerEngine(arg1:string):Promise<docker.EngineStatus>;

export function StartNginxEngine(arg1:string):Promise<website.NginxStatus>;

export function StartWebsiteDB(arg1:string,arg2:string):Promise<website.DBEngineStatus>;

export function StopDockerContainer(arg1:string,arg2:string):Promise<void>;

export function StopDockerStream(arg1:string):Promise<void>;

export function StreamDockerContainerLogs(arg1:docker.LogsRequest):Promise<string>;

export function StreamDockerContainerStats(arg1:string,arg2:string):Promise<string>;

export function StreamDockerEngineInstall(arg1:string):Promise<string>;

export function StreamWebsiteInstall(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StreamWebsiteLog(arg1:website.LogReadRequest):Promise<string>;

export function TestServerConnection(arg1:servers.SaveServerRequest):Promise<servers.ConnectionTestResult>;

export function ToggleWebsiteCronJob(arg1:website.CronToggleRequest):Promise<void>;

export function TrustServerHostKey(arg1:servers.SaveServerRequest):Promise<void>;

export function UpdateWebsiteCronJob(arg1:website.CronJobRequest):Promise<website.CronJobInfo>;

export function UploadFilesToServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteFileContent(arg1:files.WriteFileRequest):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
